// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTeqp_N2_KlaGQ_3J3tUHaKrM8jLQ8IRw',
    appId: '1:870840533908:web:5f7cada3bdf5de30f54581',
    messagingSenderId: '870840533908',
    projectId: 'cpd-assignment-d5362',
    authDomain: 'cpd-assignment-d5362.firebaseapp.com',
    databaseURL: 'https://cpd-assignment-d5362-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cpd-assignment-d5362.firebasestorage.app',
    measurementId: 'G-DGBN16PGKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYzCmO4aH9a72hfPzJ_cPhYJeLuR8gor0',
    appId: '1:870840533908:android:2459c11a226c921af54581',
    messagingSenderId: '870840533908',
    projectId: 'cpd-assignment-d5362',
    databaseURL: 'https://cpd-assignment-d5362-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cpd-assignment-d5362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4JzXwyPVw-69A09H_h8zamYQP-3iLGc',
    appId: '1:870840533908:ios:e8effbe6847dcdd6f54581',
    messagingSenderId: '870840533908',
    projectId: 'cpd-assignment-d5362',
    databaseURL: 'https://cpd-assignment-d5362-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cpd-assignment-d5362.firebasestorage.app',
    iosBundleId: 'com.example.assignmentCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4JzXwyPVw-69A09H_h8zamYQP-3iLGc',
    appId: '1:870840533908:ios:e8effbe6847dcdd6f54581',
    messagingSenderId: '870840533908',
    projectId: 'cpd-assignment-d5362',
    databaseURL: 'https://cpd-assignment-d5362-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cpd-assignment-d5362.firebasestorage.app',
    iosBundleId: 'com.example.assignmentCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTeqp_N2_KlaGQ_3J3tUHaKrM8jLQ8IRw',
    appId: '1:870840533908:web:8ca7e27a1e0b8aa2f54581',
    messagingSenderId: '870840533908',
    projectId: 'cpd-assignment-d5362',
    authDomain: 'cpd-assignment-d5362.firebaseapp.com',
    databaseURL: 'https://cpd-assignment-d5362-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cpd-assignment-d5362.firebasestorage.app',
    measurementId: 'G-JFFF791VEW',
  );
}
